### ISSUE TITLE
DB error

### ISSUE THREAD

**Issue by dollannn** [WaterChick/CRewardR#1]
[22:24:04 WARN]: [CReward] Plugin CReward v2.2.2 generated an exception while executing task 23
java.lang.NullPointerException: Cannot invoke "cz.waterchick.creward.CReward.Reward.getName()" because "reward" is null
        at cz.waterchick.creward.CReward.managers.DBManager.getTime(DBManager.java:139) ~[CRewardR.jar:?]
        at cz.waterchick.creward.CReward.Main.decrease(Main.java:359) ~[CRewardR.jar:?]
        at cz.waterchick.creward.CReward.Main$1.run(Main.java:74) ~[CRewardR.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by WaterChick** [comment]
Hi,

Please contact me on discord: kevii#6312

**Comment by WaterChick** [comment]
Don't forget to have the same reward names on other servers conected to the database too.
Check the config. Database writes data only (Time left), not rewards.

**Comment by dollannn** [comment]
There is only one server, it has created a table for daily and it is stuck at the 24h worth of seconds for myself and errors each second.

**Comment by WaterChick** [comment]
Error appears because it cant match the table name with a reward name. Do the names match ?

**Comment by WaterChick** [comment]
They may be an error when loading the rewards, send me your config.yml please.

**Comment by dollannn** [comment]
I did not change a thing and just waited 48hrs and did a restart with mysql enabled and it worked

**Comment by WaterChick** [comment]
Strange, the MySQL feature is new and may be buggy. Please keep me updated with more MySQL errors.

**Comment by dollannn** [comment]
Sorry, after another restart it happened again. I cannot paste all my details but here you go:
```
Messages:
  Prefix: '&d&lDAILY &8» '
  claim: '&aReward claimed!'
  noClaim: '&cYou can not claim this reward yet! &7(%creward_time%)'
  configReload: '&7Config reloaded'
  reset: '&7%player_name%''s reward time has been reseted'
  noPerm: '&cYou do not have permission to execute this command'
  readyToClaim: '&aReady to claim!'
  notify: '&7You can claim &a%creward_amount% &7reward(s)!'
  autoPickup: '&7Auto-Claimed &a%rewards% &7reward(s) (Premium)'
#Auto picks up all rewards for player after joining
#If false, player gets only a notification
Autopickup:
  enabled: false
  permission: creward.autoclaim
#Should the GUI close after claiming a reward
closeOnClaim: true
GUI:
  title: '&8» &d&lDAILY'
  rows: 5
  #Glass Filler for the GUI
  Filler:
    Enable: true
    Slots:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 17
      - 18
      - 26
      - 27
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      
    Item:
      Material: MAGENTA_STAINED_GLASS_PANE
  Rewards:
    daily:
      Item:
        #Reward claimable
        yesClaim:
          Item:
            Material: EMERALD_BLOCK
            skullData: '%player_name%'
            amount: 1
          Title: '&a&lDaily reward'
          Lore: |2-

            &7&oClick to claim
          Slot: 22
          #Permission to claim this reward
          Permission: ''
        #Waiting for reward
        noClaim:
          Item:
            Material: COAL_BLOCK
            skullData: '%player_name%'
            amount: 1
          Title: '&c&lDaily reward'
          Lore: |2-
            &8 Du har redan claimat denna reward
            &7&o Kom tillbaka &f%creward_time%
          Slot: 22
        #No permission for reward
        noPermClaim:
          Item:
            Material: BARRIER
            skullData: '%player_name%'
            amount: 1
          Title: '&cDaily reward'
          Lore: |2-

            &cNo permission
          Slot: 22
      #Commands executed after claiming
      Commands:
        - level addexp %player_name% 10000
      #Cooldown for the reward, in seconds
      Cooldown: 86400
  #Items for designing the GUI
  otherItems:

#    item1:
#      Item:
#        ==: org.bukkit.inventory.ItemStack
#        type: IRON_INGOT
#        meta:
#          ==: ItemMeta
#          meta-type: UNSPECIFIC
#          display-name: '&aItem 1'
#          lore:
#            - '&cLore'
#            - '&eLore2'
#      Slot: 12
Sounds:
  OPEN_MENU:
    Sound: BLOCK_CHEST_OPEN
    Volume: 1
    Pitch: 4
  REWARD_PICKUP:
    Sound: ENTITY_CHICKEN_EGG
    Volume: 1
    Pitch: 4
MySQL:
  enable: true
  username: playpark_minecraft
  password: 'PASSWORD'
  adress: ADRESS
  db: playpark_minecraft


```
